FROM heroku/heroku:16

ARG OTP_VERSION
ARG ELIXIR_VERSION
ARG REPO_URL

ENV OTP_VERSION="${OTP_VERSION}"
ENV ELIXIR_VERSION="${ELIXIR_VERSION}"
ENV STACK="heroku-16"

# Elixir requires a UTF8 locale
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

RUN mkdir /buildpack
RUN mkdir /cache
RUN mkdir /env

RUN git clone "${REPO_URL}" /app
WORKDIR /app

RUN mkdir /buildpack/{bin,lib,profile,tests}

COPY ./bin/ /buildpack/bin/
COPY ./lib/ /buildpack/lib/
COPY ./profile/ /buildpack/profile/

RUN /buildpack/bin/compile /app /cache /env

COPY ./tests/ /buildpack/tests/

RUN /buildpack/tests/sanity-checks.sh /app

CMD /app/bin/elixir_release
